font_family tamzen
font_size 9.0
bold_font auto

window_padding_width 10
disable_ligatures never

confirm_os_window_close 0

remember_window_size  no
initial_window_width  340
initial_window_height 150
