#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Polybar manage=off border=off layer=above sticky=on




bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap          5

bspc config top_padding -6
bspc config bottom_padding -6
bspc config left_padding -6
bspc config right_padding -6

bspc config focused_border_color "#333333"
bspc config normal_border_color "#111111"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap latam &
pkill picom 
picom &
$HOME/.config/bspwm/scripts/monitor_setup.sh &
pkill polybar 
~/.config/polybar/launch.sh --colorblocks &
(
  while ! xdo id -N Polybar; do sleep 0.2; done
  # Esto ahora sí funcionará permanentemente porque bspwm no forzará la barra hacia abajo
  xdo raise -N Polybar
  polybar-msg cmd hide
) &
$HOME/.config/bspwm/scripts/hot_corner_bar.sh &


